#!/bin/zsh
echo "zsh_aliases"

alias resap="sudo apachectl -k restart"

alias edap="sudo nano /usr/local/etc/httpd/httpd.conf"
alias edvh="sudo nano /usr/local/etc/httpd/extra/httpd-vhosts.conf"

alias ed56="sudo nano /usr/local/etc/php/5.6/php.ini"
alias ed70="sudo nano /usr/local/etc/php/7.0/php.ini"
alias ed71="sudo nano /usr/local/etc/php/7.1/php.ini"
alias ed72="sudo nano /usr/local/etc/php/7.2/php.ini"

alias edxdb56="sudo nano /usr/local/etc/php/5.6/conf.d/ext-xdebug.ini"
alias edxdb70="sudo nano /usr/local/etc/php/7.0/conf.d/ext-xdebug.ini"
alias edxdb71="sudo nano /usr/local/etc/php/7.1/conf.d/ext-xdebug.ini"
alias edxdb72="sudo nano /usr/local/etc/php/7.2/conf.d/ext-xdebug.ini"

alias stodb="brew services stop mariadb"
alias stadb="brew services start mariadb"
#_______________________________________________________________________________________________________________________
#_______________________________________________________________________________________________________________________
#
##			Mho_Extensions
#_______________________________________________________________________________________________________________________
#
##			File & Directoryshortcuts
#
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias cl="clear"
alias "aliases"="nano ~/.home/aliases "
alias "functions"="nano ~/.home/functions "
alias vhosts="sudo nano /usr/local/etc/httpd/extra/httpd-vhosts.conf"

#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
##			common CLI shorthands
#
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias cl="clear"
alias "aliases"="nano ~/.home/aliases "
alias "functions"="nano ~/.home/functions "
alias vhosts="sudo nano /usr/local/etc/httpd/extra/httpd-vhosts.conf"
alias ll="ls -lah"
alias pwd="pwd -P"
alias cmp="composer"

#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
##			GIT.aliases
#
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias gs="git status"
alias gd="git diff"
alias gp="git push"
alias gcm"git commit"

#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
##			Magento2 aliases
#
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias mg="bin/magento"
alias mg-su="mg setup:upgrade"
alias mg-ccf="mg cache:clean && bin/magento cache:flush"

#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
## 			L5 Aliases
#
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias "ar"="php artisan"
#
#_______________________________________________________________________________________________________________________
