#!/bin/zsh
echo "zsh_functions"


function mg () {

        current_date_time="`date "+%Y-%m-%d %H:%M:%S"`";
	echo "________________________________________________________________________";
        echo "|"+$current_date_time;
	echo "|";
	echo "|_______________________________________________________________________";
        bin/magento $1 $2 $3 $4
}